services:
  portfolio:
    image: ghcr.io/giovanivercauteren/portfolio:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`giovani.vercauteren.io`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=le"
    networks:
      - proxy

networks:
  proxy:
    external: true